# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.failure import Failure  # noqa: E501
from swagger_client.rest import ApiException


class TestFailure(unittest.TestCase):
    """Failure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailure(self):
        """Test Failure"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.failure.Failure()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
