# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.historical_api import HistoricalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoricalApi(unittest.TestCase):
    """HistoricalApi unit test stubs"""

    def setUp(self):
        self.api = api.historical_api.HistoricalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_historical(self):
        """Test case for get_historical

        Get Historical Aggregate Data by Year  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
