# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.failures_api import FailuresApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFailuresApi(unittest.TestCase):
    """FailuresApi unit test stubs"""

    def setUp(self):
        self.api = api.failures_api.FailuresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_failures(self):
        """Test case for get_failures

        Get detail on historical bank failures from 1934 to present.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
