# coding: utf-8

# flake8: noqa

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.failures_api import FailuresApi
from swagger_client.api.historical_api import HistoricalApi
from swagger_client.api.structure_api import StructureApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.failure import Failure
from swagger_client.models.institution import Institution
from swagger_client.models.location import Location
from swagger_client.models.metadata import Metadata
from swagger_client.models.summary import Summary
from swagger_client.models.totals import Totals
