# coding: utf-8

# flake8: noqa
"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.failure import Failure
from swagger_client.models.institution import Institution
from swagger_client.models.location import Location
from swagger_client.models.metadata import Metadata
from swagger_client.models.summary import Summary
from swagger_client.models.totals import Totals
