# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Metadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'parameters': 'object',
        'index': 'object'
    }

    attribute_map = {
        'total': 'total',
        'parameters': 'parameters',
        'index': 'index'
    }

    def __init__(self, total=None, parameters=None, index=None):  # noqa: E501
        """Metadata - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._parameters = None
        self._index = None
        self.discriminator = None
        if total is not None:
            self.total = total
        if parameters is not None:
            self.parameters = parameters
        if index is not None:
            self.index = index

    @property
    def total(self):
        """Gets the total of this Metadata.  # noqa: E501

        Total query result count  # noqa: E501

        :return: The total of this Metadata.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this Metadata.

        Total query result count  # noqa: E501

        :param total: The total of this Metadata.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def parameters(self):
        """Gets the parameters of this Metadata.  # noqa: E501

        Query parameters supplied  # noqa: E501

        :return: The parameters of this Metadata.  # noqa: E501
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this Metadata.

        Query parameters supplied  # noqa: E501

        :param parameters: The parameters of this Metadata.  # noqa: E501
        :type: object
        """

        self._parameters = parameters

    @property
    def index(self):
        """Gets the index of this Metadata.  # noqa: E501


        :return: The index of this Metadata.  # noqa: E501
        :rtype: object
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this Metadata.


        :param index: The index of this Metadata.  # noqa: E501
        :type: object
        """

        self._index = index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Metadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Metadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
