# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class FailuresApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_failures(self, **kwargs):  # noqa: E501
        """Get detail on historical bank failures from 1934 to present.  # noqa: E501

        Returns details on failed financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_failures(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter criteria that refines the records returned.  Examples: * Filter by Location               `CITYST:\"MEMPHIS, TN\"`   * Filter by institution fail year range   `FAILYR:[\"2015\" TO \"2016\"]` 
        :param str fields: Comma delimited list of fields of failed financial institutions to return.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str total_fields: Fields to sum up (in a totals response object). Only numeric columns are valid.
        :param str subtotal_by: The field by which data will be subtotaled (in totals response object). Only categorical values should be used.
        :param str agg_by: The field(s) by which data will be aggregated. Valid values are 'FAILYR' or 'FAILYR,PSTALP'.
        :param str agg_term_fields: The field(s) for which aggregations will be counted for each unique term.
        :param str agg_sum_fields: The field(s) for which aggregations will be summed or aggregated.
        :param int agg_limit: The limit on how many aggregated results will be displayed
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_failures_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_failures_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_failures_with_http_info(self, **kwargs):  # noqa: E501
        """Get detail on historical bank failures from 1934 to present.  # noqa: E501

        Returns details on failed financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_failures_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter criteria that refines the records returned.  Examples: * Filter by Location               `CITYST:\"MEMPHIS, TN\"`   * Filter by institution fail year range   `FAILYR:[\"2015\" TO \"2016\"]` 
        :param str fields: Comma delimited list of fields of failed financial institutions to return.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str total_fields: Fields to sum up (in a totals response object). Only numeric columns are valid.
        :param str subtotal_by: The field by which data will be subtotaled (in totals response object). Only categorical values should be used.
        :param str agg_by: The field(s) by which data will be aggregated. Valid values are 'FAILYR' or 'FAILYR,PSTALP'.
        :param str agg_term_fields: The field(s) for which aggregations will be counted for each unique term.
        :param str agg_sum_fields: The field(s) for which aggregations will be summed or aggregated.
        :param int agg_limit: The limit on how many aggregated results will be displayed
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filters', 'fields', 'sort_by', 'sort_order', 'limit', 'offset', 'total_fields', 'subtotal_by', 'agg_by', 'agg_term_fields', 'agg_sum_fields', 'agg_limit', 'format', 'download', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_failures" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filters' in params:
            query_params.append(('filters', params['filters']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sort_order', params['sort_order']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'total_fields' in params:
            query_params.append(('total_fields', params['total_fields']))  # noqa: E501
        if 'subtotal_by' in params:
            query_params.append(('subtotal_by', params['subtotal_by']))  # noqa: E501
        if 'agg_by' in params:
            query_params.append(('agg_by', params['agg_by']))  # noqa: E501
        if 'agg_term_fields' in params:
            query_params.append(('agg_term_fields', params['agg_term_fields']))  # noqa: E501
        if 'agg_sum_fields' in params:
            query_params.append(('agg_sum_fields', params['agg_sum_fields']))  # noqa: E501
        if 'agg_limit' in params:
            query_params.append(('agg_limit', params['agg_limit']))  # noqa: E501
        if 'format' in params:
            query_params.append(('format', params['format']))  # noqa: E501
        if 'download' in params:
            query_params.append(('download', params['download']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/failures', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
