# coding: utf-8

"""
    FDIC Bank Data API (Beta)

    API to serve banking industry data to the public.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: PublicDataFeedback@fdic.gov
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class StructureApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def search_institutions(self, **kwargs):  # noqa: E501
        """Get Financial Institutions  # noqa: E501

        Returns a list of financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_institutions(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter for the bank search. Examples: * Filter by State name   `STNAME:\"West Virginia\"`     * Filter for any one of multiple State names   `STNAME:(\"West Virginia\",\"Delaware\")`     * Filter by last updated within an inclusive date range   `DATEUPDT:[\"2010-01-01\" TO \"2010-12-31\"]` * Filter for deposits over 50,000,000 (50000 thousands of dollars)   `DEP:[50000 TO *]` 
        :param str search: Flexible text search against institution records - currently only supporting name search.  Search supports text search and fuzzy matching, as opposed to filters that are exact matches. Examples: * Search by name `NAME: Island` * Search by name (fuzzy match) `NAME: Iland` 
        :param str fields: Comma delimited list of fields to search.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_institutions_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_institutions_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_institutions_with_http_info(self, **kwargs):  # noqa: E501
        """Get Financial Institutions  # noqa: E501

        Returns a list of financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_institutions_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter for the bank search. Examples: * Filter by State name   `STNAME:\"West Virginia\"`     * Filter for any one of multiple State names   `STNAME:(\"West Virginia\",\"Delaware\")`     * Filter by last updated within an inclusive date range   `DATEUPDT:[\"2010-01-01\" TO \"2010-12-31\"]` * Filter for deposits over 50,000,000 (50000 thousands of dollars)   `DEP:[50000 TO *]` 
        :param str search: Flexible text search against institution records - currently only supporting name search.  Search supports text search and fuzzy matching, as opposed to filters that are exact matches. Examples: * Search by name `NAME: Island` * Search by name (fuzzy match) `NAME: Iland` 
        :param str fields: Comma delimited list of fields to search.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filters', 'search', 'fields', 'sort_by', 'sort_order', 'limit', 'offset', 'format', 'download', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_institutions" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filters' in params:
            query_params.append(('filters', params['filters']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sort_order', params['sort_order']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'format' in params:
            query_params.append(('format', params['format']))  # noqa: E501
        if 'download' in params:
            query_params.append(('download', params['download']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/institutions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def search_locations(self, **kwargs):  # noqa: E501
        """Get Institution Locations  # noqa: E501

        Returns locations/branches of financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_locations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter for the location search.
        :param str fields: Comma delimited list of fields to return.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.search_locations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.search_locations_with_http_info(**kwargs)  # noqa: E501
            return data

    def search_locations_with_http_info(self, **kwargs):  # noqa: E501
        """Get Institution Locations  # noqa: E501

        Returns locations/branches of financial institutions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.search_locations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filters: The filter for the location search.
        :param str fields: Comma delimited list of fields to return.
        :param str sort_by: Field name by which to sort returned data
        :param str sort_order: Indicator if ascending (ASC) or descending (DESC)
        :param int limit: The number of records to return. Default is 10 and maximum is 10,000.
        :param int offset: The offset of page to return.
        :param str format: The format of the data to return.
        :param str download: Whether the data should be downloaded as a file.
        :param str filename: The filename to use when downloading data.
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filters', 'fields', 'sort_by', 'sort_order', 'limit', 'offset', 'format', 'download', 'filename']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_locations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filters' in params:
            query_params.append(('filters', params['filters']))  # noqa: E501
        if 'fields' in params:
            query_params.append(('fields', params['fields']))  # noqa: E501
        if 'sort_by' in params:
            query_params.append(('sort_by', params['sort_by']))  # noqa: E501
        if 'sort_order' in params:
            query_params.append(('sort_order', params['sort_order']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'format' in params:
            query_params.append(('format', params['format']))  # noqa: E501
        if 'download' in params:
            query_params.append(('download', params['download']))  # noqa: E501
        if 'filename' in params:
            query_params.append(('filename', params['filename']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/csv'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/locations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
